import { type NextPage } from "next";
import Head from "next/head";
import { motion } from "framer-motion";
import { useSession } from "next-auth/react";

import Feed from "~/components/feed";
import Login from "~/components/login";
import BottomTabs from "~/components/bottom-tabs";
import { FaPlus } from "react-icons/fa";
import Header from "~/components/header";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <motion.section
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.25 }}
      >
        {sessionData && <Header />}
        {sessionData ? <Feed /> : <Login />}
        {sessionData && <BottomTabs />}
      </motion.section>
    </>
  );
};

export default Home;
